# Thalloo - Geotemporal Mapping Tool
#
# This project uses Jekyll to integrate with GitHub Pages.
# Configure the basic settings below to configure your copy.

# Your site settings
title: Thalloo Maps
description: > # this means to ignore newlines until "baseurl:"
  A range of environmental datasets that can be visualised across space and through time.
baseurl: "/thalloo" # the subpath of your site, e.g. /blog
url: "http://acm.im" # the base hostname & protocol for your site

# Internal configuration
markdown: kramdown
collections:
  maps:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"